apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
      - image: {{ .Values.image }}
        name: {{ .Values.name }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: {{ .Values.service.name }}
          protocol: TCP
