apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.name }}
  labels:
    release: kube-prometheus-kube-prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  endpoints:
  - port: {{ .Values.service.name }}
