{
 "title": "podsPerNodeNamespace",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "exported_namespace",
    "query": {
     "query": "label_values(pods_per_node{job=\"nodestats\"}, exported_namespace)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(pods_per_node{job=\"nodestats\"}, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "podsPerNode by Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "podsPerNode by Namespace",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (pods_per_node{exported_namespace=\"$exported_namespace\"})"
    }
   ]
  },
  {
   "title": "Pods per Namespace",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_namespace) (pods_per_node{node=\"$node\"})"
    }
   ]
  },
  { "title": "static", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "pods per node",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum by (node) (pods_per_node)" }
   ]
  },
  {
   "title": "pods per namespace",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_namespace) (pods_per_node)"
    }
   ]
  }
 ]
}